force-app/main/default/objects/LicenseList__mdt/LicenseList__mdt.object-meta.xml
<CustomObject>
    <description>This type translate the coded name of Salesforce licence into one chosen by the customer</description>
    <label>LicenseList</label>
    <pluralLabel>LicenseList</pluralLabel>
</CustomObject>

force-app/main/default/objects/LicenseList__mdt/fields/LicenseCategory__c.field-meta.xml
<CustomField>
    <fullName>LicenseCategory__c</fullName>
    <label>LicenseCategory</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Core Licenses</fullName>
            </value>
            <value>
                <fullName>Experience Cloud</fullName>
            </value>
            <value>
                <fullName>Features</fullName>
            </value>
            <value>
                <fullName>Key Licenses</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Analytics</fullName>
            </value>
            <value>
                <fullName>B2B Commerce</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <default>true</default>
                <label>Other</label>
            </value>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>Field Service</fullName>
            </value>
            <value>
                <fullName>Salesforce Maps</fullName>
            </value>
            <value>
                <fullName>myTrailhead</fullName>
            </value>
            <value>
                <fullName>Salesforce CPQ</fullName>
            </value>
            <value>
                <fullName>Slack</fullName>
            </value>
            <value>
                <fullName>Energy &amp; Utility Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseList__mdt/fields/TranslatedLicenseName__c.field-meta.xml
<CustomField>
    <fullName>TranslatedLicenseName__c</fullName>
    <label>TranslatedLicenseName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/OrgMonitoring__c.object-meta.xml
<CustomObject>
    <description>This object is used to store licences and limits information for Org Monitoring</description>
    <label>OrgMonitoring</label>
    <nameField>
        <displayFormat>S{000000000}</displayFormat>
        <label>Snapshot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrgsMonitoring</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgMonitoring__c/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/Latest__c.field-meta.xml
<CustomField>
    <fullName>Latest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if this is the latest Snapshot produced</description>
    <label>Latest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/LicenseCategory__c.field-meta.xml
<CustomField>
    <fullName>LicenseCategory__c</fullName>
    <description>This field permit to group different licences under the same categpry</description>
    <label>LicenseCategory</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/OrgCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>OrgCreatedDate__c</fullName>
    <description>The date of creation of the org.</description>
    <label>OrgCreatedDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/OrgDomainName__c.field-meta.xml
<CustomField>
    <fullName>OrgDomainName__c</fullName>
    <label>OrgDomainName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/OrgID__c.field-meta.xml
<CustomField>
    <fullName>OrgID__c</fullName>
    <label>Org ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/OrgName__c.field-meta.xml
<CustomField>
    <fullName>OrgName__c</fullName>
    <label>Org Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/TimestampText__c.field-meta.xml
<CustomField>
    <fullName>TimestampText__c</fullName>
    <label>TimestampText</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/TranslatedLicenseName__c.field-meta.xml
<CustomField>
    <fullName>TranslatedLicenseName__c</fullName>
    <description>This field contains a &quot;redeable&quot; name for licences who are stored with a prefix under their name.</description>
    <label>TranslatedLicenseName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of limit</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <label>Units</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/OrgToMonitor__mdt.object-meta.xml
<CustomObject>
    <description>This Metadata contains the list of all orgs you want to monitor</description>
    <label>OrgToMonitor</label>
    <pluralLabel>OrgsToMonitor</pluralLabel>
</CustomObject>

force-app/main/default/objects/OrgToMonitor__mdt/fields/apiVersion__c.field-meta.xml
<CustomField>
    <fullName>apiVersion__c</fullName>
    <label>Version API</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B2B</fullName>
                <default>true</default>
                <label>B2B</label>
            </value>
            <value>
                <fullName>B2C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>The country where the Org located</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Antigua And Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Cuba</fullName>
            </value>
            <value>
                <fullName>Czech Republic (Czechia)</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>Estonia</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Org_Id__c</fullName>
    <description>This is the unique OrgId of the Org to Monitor</description>
    <label>Org ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Org_Name__c.field-meta.xml
<CustomField>
    <fullName>Org_Name__c</fullName>
    <description>This is the Name of the Org</description>
    <label>Domain Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/OrgCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>OrgCreatedDate__c</fullName>
    <description>Date of creation of the Org</description>
    <inlineHelpText>Creation date of the Organization</inlineHelpText>
    <label>OrgCreatedDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/OrgMonitoringExtractLicenses.cls
/*-------------------------------------------------------------------------------------
Author:        Salvatore Aversano
Company:       Salesforce.com
Description:   Apex class used to extract the usage of Licenses from following objects:
               - UserLicenses
               - PermissionSetLicenses
               - PackageLicense (-- retired)
Test Class:    OrgMoniotoringExtractLicenses_Test
Version:       1.0
History
10/05/2022     Salvatore Aversano    Create version
----------------------------------------------------------------------------------------*/

public with sharing class OrgMonitoringExtractLicenses 
{
   // Wrapper Class for Licenses User
   public class LicenseCollection 
   {
      public Integer totalSize;
      public Boolean done;
      public List<LicenseRecords> records;
   }
   public class LicenseAttributes {
       public String type;
       public String url;
   }

   public class LicenseRecords {
       public LicenseAttributes attributes;
       public String Status;
       public String MasterLabel;
       public Integer TotalLicenses;
       public Integer UsedLicenses;
   }

   public static LicenseCollection parselicense (String json) {
      return (LicenseCollection) System.JSON.deserialize(json, LicenseCollection.class);
   }

   // Wrapper Class for Licenses Package 
   public class LicensePackageCollection {
      public Integer totalSize;
      public Boolean done;
      public List<LicensePackageRecords> records;
   }
   public class LicensePackageAttributes {
       public String type;
       public String url;
   }

   public class LicensePackageRecords {
      public LicensePackageAttributes attributes;
      public String NamespacePrefix;
      public Integer AllowedLicenses;
      public Integer UsedLicenses;
      public String Status;
   }

      public static LicensePackageCollection parselicensepackage (String json) {
      return (LicensePackageCollection) System.JSON.deserialize(json, LicensePackageCollection.class);
   }

   public static List<OrgMonitoring__c> execute (OrgToMonitor__mdt org)
   {
     
      // GET THE DEFAULT PICKLIST VALUE FOR LICENSE CATGORY
      String defaultCategory;
      Schema.DescribeFieldResult F = LicenseList__mdt.LicenseCategory__c.getDescribe();
      List <Schema.PicklistEntry> pickVals = F.getPicklistValues();        
      for (Schema.PicklistEntry pv: pickVals) {
          if (pv.isDefaultValue()) {
            defaultCategory = pv.getValue();
          }    
      }

      List<OrgMonitoring__c> lorgmonitoring = new List<OrgMonitoring__c>();
      List<OrgMonitoring__c> lorgmon = new List<OrgMonitoring__c>();
      
      // GET LICENSES UTILIZATION FROM USER LICENSE OBJECT
      lorgmon = processLicenses(org,defaultCategory);
      lorgmonitoring.addAll(lorgmon);
       
      // GET LICENSES UTILIZATION FROM PERMISSION SET LICENSE
      lorgmon.clear();
      lorgmon = processLicensesfromPset(org,defaultCategory);
      lorgmonitoring.addAll(lorgmon);

      // GET LICENSES UTILIZATION FROM PACKAGE LICENSE
      // SAV : August 22, 200
         // These licences are PER SITE. They are assigned via Permission Set licence. 
         // This extract is not needed ! 
     // lorgmon.clear();
     // lorgmon = processLicensesfromPackage(org,defaultCategory);
     // lorgmonitoring.addAll(lorgmon);

      return lorgmonitoring;
   }   
           
   public static List<OrgMonitoring__c> processLicenses (OrgToMonitor__mdt org, String defaultCategory)
   {
      system.debug( '#### Processing Licenses from User License ####');
   
      /*   =======================================================================
                     GET LICENSES USAGE FROM USER LICENSES OBJECT
        ======================================================================= */

      List<OrgMonitoring__c> lListLicenses = new List<OrgMonitoring__c>();
      String LicenseNamewithUnderscore = '';
      String sEndPoint = 'callout:' + org.DeveloperName + '/services/data/v' + org.Apiversion__c + '.0/query/?q=SELECT+Status,+MasterLabel,+TotalLicenses,+UsedLicenses+FROM+UserLicense+where+Status+=+\'Active\'';
            
      // Get Connexion and Run the EndPoint
      HttpRequest feedRequestLicense = new HttpRequest();
      feedRequestLicense.setEndpoint(sEndPoint);
      feedRequestLicense.setMethod('GET');
      Http http = new Http();
      HTTPResponse feedResponseLicense = new HTTPResponse();
        if (  Test.isRunningTest() ) {
         feedResponseLicense.setStatusCode( 200 );
         feedResponseLicense.setBody ('{"totalSize":24,"done":true,"records":[{"attributes":{"type":"UserLicense","url":"/services/data/v53.0/sobjects/UserLicense/1007Q000002DbsLQAS"},"Status":"Active","MasterLabel":"Salesforce Platform","TotalLicenses":3,"UsedLicenses":0},{"attributes":{"type":"UserLicense","url":"/services/data/v53.0/sobjects/UserLicense/1007Q000002DbsKQAS"},"Status":"Active","MasterLabel":"Cloud Integration User","TotalLicenses":1,"UsedLicenses":0} ]}');
        } else { feedResponseLicense = http.send(feedRequestLicense);}
      
        while (feedResponseLicense.getStatusCode() == 302) {
            feedRequestLicense.setEndpoint(feedResponseLicense.getHeader('Location'));
            feedResponseLicense = new Http().send(feedRequestLicense);
      }
        
      if ( feedResponseLicense.getStatusCode() == 200 )
      {
         LicenseCollection license = (LicenseCollection)JSON.deserialize(feedResponseLicense.getBody(), LicenseCollection.class); 
         
         for (integer i=0 ; i < license.records.size() ; i++) {
           
            OrgMonitoring__c orgmonitor = new OrgMonitoring__c();
            orgmonitor.OrgID__c = org.Org_Id__c;
            orgmonitor.OrgName__c = org.Label;
            orgmonitor.OrgDomainName__c = org.Org_Name__c;
            orgmonitor.Country__c = org.Country__c;
            orgmonitor.BusinessUnit__c = org.Business_Unit__c;
            orgmonitor.Timestamp__c = datetime.now();
            orgmonitor.TimestampText__c = String.valueOf( datetime.now().format('yy-MM-dd HH:mm') );
            orgmonitor.Type__c = 'License';
            orgmonitor.Name__c = license.records[i].MasterLabel;
            orgmonitor.TranslatedLicenseName__c = license.records[i].MasterLabel;
            orgmonitor.LicenseCategory__c = defaultCategory;
            orgmonitor.Total__c = license.records[i].TotalLicenses;
            orgmonitor.Used__c = license.records[i].UsedLicenses;
            orgmonitor.Remaining__c = license.records[i].TotalLicenses - license.records[i].UsedLicenses;
            orgmonitor.Status__c = license.records[i].Status;
            orgmonitor.Units__c = 'UserLicense';
            orgmonitor.Latest__c = true;
            // Replace spaces with _ for each value of licence
            // system.debug( 'Licence Name : ' +orgmonitor.Name__c);
            LicenseNamewithUnderscore = orgmonitor.Name__c.replace (' ', '_');
            LicenseNamewithUnderscore = LicenseNamewithUnderscore.replace ('-', 'x');
            if(LicenseNamewithUnderscore.length() > 40 ){
               LicenseNamewithUnderscore = LicenseNamewithUnderscore.substring(0,40);
            }
            LicenseList__mdt tln = LicenseList__mdt.getInstance(LicenseNamewithUnderscore );
            if (tln != null) {
                 orgmonitor.TranslatedLicenseName__c = tln.TranslatedLicenseName__c;
                 orgmonitor.LicenseCategory__c = tln.LicenseCategory__c;
            }

            // When license name is Salesforce, then store the value of organization created date
            if (orgmonitor.Name__c == 'Salesforce') {
               orgmonitor.OrgCreatedDate__c = org.OrgCreatedDate__c;
            }
            
            lListLicenses.add(orgmonitor);
         }
      } else {
          System.debug ('#### Error reaching endpoint for Licenses ==> ' +sEndPoint);
          System.debug ('#### Error code ==> ' +feedResponseLicense.getStatusCode());
         } 
      return lListLicenses;
    }
    
    public static List<OrgMonitoring__c> processLicensesfromPset (OrgToMonitor__mdt org, String defaultCategory)
    {
        /* =======================================================================
                        GET LICENSES USAGE FROM PERMISSION SET LICENSE
           =======================================================================
        */
        
        system.debug( '#### Processing Licenses from Permission Set Licenses ####');
        List<OrgMonitoring__c> lListLicensesPset = new List<OrgMonitoring__c>();
        String LicenseNamewithUnderscore = '';
        String sEndPoint = 'callout:' + org.DeveloperName + '/services/data/v' + org.Apiversion__c + '.0/query/?q=SELECT+Status,+MasterLabel,+TotalLicenses,+UsedLicenses+FROM+PermissionSetLicense+where+Status+=+\'Active\'';
        
        // Get Connexion and Run the EndPoint
        HttpRequest feedRequestLicense = new HttpRequest();
        feedRequestLicense.setEndpoint(sEndPoint);
        feedRequestLicense.setMethod('GET');
        Http http = new Http();
        HTTPResponse feedResponseLicense = new HTTPResponse();
        if (  Test.isRunningTest() ) {
         feedResponseLicense.setStatusCode( 200 );
         feedResponseLicense.setBody ('{"totalSize":24,"done":true,"records":[{"attributes":{"type":"UserLicense","url":"/services/data/v53.0/sobjects/UserLicense/1007Q000002DbsLQAS"},"Status":"Active","MasterLabel":"Salesforce Platform","TotalLicenses":3,"UsedLicenses":0},{"attributes":{"type":"UserLicense","url":"/services/data/v53.0/sobjects/UserLicense/1007Q000002DbsKQAS"},"Status":"Active","MasterLabel":"Cloud Integration User","TotalLicenses":1,"UsedLicenses":0} ]}');
        } else { feedResponseLicense = http.send(feedRequestLicense);}
      
        while (feedResponseLicense.getStatusCode() == 302) {
            feedRequestLicense.setEndpoint(feedResponseLicense.getHeader('Location'));
            feedResponseLicense = new Http().send(feedRequestLicense);
      }
        
        if ( feedResponseLicense.getStatusCode() == 200 )
        {
           LicenseCollection license = (LicenseCollection)JSON.deserialize(feedResponseLicense.getBody(), LicenseCollection.class); 
           
           for (integer i=0 ; i < license.records.size() ; i++) {
              // system.debug( 'lListLicensesPset: ' +license.records[i].MasterLabel);
              OrgMonitoring__c orgmonitor = new OrgMonitoring__c();
              orgmonitor.OrgID__c = org.Org_Id__c;
              orgmonitor.OrgName__c = org.Label;
              orgmonitor.OrgDomainName__c = org.Org_Name__c;
              orgmonitor.Country__c = org.Country__c;
              orgmonitor.BusinessUnit__c = org.Business_Unit__c;
              orgmonitor.Timestamp__c = datetime.now();
              orgmonitor.TimestampText__c = String.valueOf( datetime.now().format('yy-MM-dd HH:mm') );
              orgmonitor.Type__c = 'License';
              orgmonitor.Name__c = license.records[i].MasterLabel;
              orgmonitor.TranslatedLicenseName__c = license.records[i].MasterLabel;
              orgmonitor.LicenseCategory__c = defaultCategory;
              orgmonitor.Total__c = license.records[i].TotalLicenses;
              orgmonitor.Used__c = license.records[i].UsedLicenses;
              orgmonitor.Remaining__c = license.records[i].TotalLicenses - license.records[i].UsedLicenses;
              orgmonitor.Status__c = license.records[i].Status;
              orgmonitor.Units__c = 'PsetLicense';
              orgmonitor.Latest__c = true;
              // Replace spaces with _ for each value of licence
              LicenseNamewithUnderscore = orgmonitor.Name__c.replace (' ', '_');
              LicenseNamewithUnderscore = LicenseNamewithUnderscore.replace ('-', 'x');
              if(LicenseNamewithUnderscore.length() > 40 ){
               LicenseNamewithUnderscore = LicenseNamewithUnderscore.substring(0,40);
              }
              LicenseList__mdt tln = LicenseList__mdt.getInstance(LicenseNamewithUnderscore);
              if (tln != null) {
                 orgmonitor.TranslatedLicenseName__c = tln.TranslatedLicenseName__c;
                 orgmonitor.LicenseCategory__c = tln.LicenseCategory__c;
              }
              lListLicensesPset.add(orgmonitor);
           }
        } else {
            System.debug ('#### Error reaching endpoint for Permission Set Licenses ==> ' +sEndPoint);
            System.debug ('#### Error code ==> ' +feedResponseLicense.getStatusCode());
           } 
        return lListLicensesPset;
    }
    
       /* =======================================================================
                        GET LICENSES USAGE FROM PACKAGE LICENSE OBJECT
           =======================================================================
        */
        
       
    /* public static List<OrgMonitoring__c> processLicensesfromPackage (OrgToMonitor__mdt org, String defaultCategory)
    {
        
       system.debug( '#### Processing Licenses from Package License ####');
        List<OrgMonitoring__c> lListLicensesPackage = new List<OrgMonitoring__c>();
        String LicenseNamewithUnderscore = '';
        String sEndPoint = 'callout:' + org.DeveloperName + '/services/data/v' + org.Apiversion__c + '.0/query/?q=SELECT+NamespacePrefix,+AllowedLicenses,+UsedLicenses,+Status+FROM+PackageLicense+where+Status+=+\'Active\'';
        //+and+AllowedLicenses+!=+-1
        // Get Connexion and Run the EndPoint
        HttpRequest feedRequestLicense = new HttpRequest();
        feedRequestLicense.setEndpoint(sEndPoint);
        feedRequestLicense.setMethod('GET');
        Http http = new Http();
        HTTPResponse feedResponseLicense = new HTTPResponse();
        if (  Test.isRunningTest() ) {
         feedResponseLicense.setStatusCode( 200 );
         feedResponseLicense.setBody ('{"totalSize":26,"done":true,"records":[ {"attributes":{"type":"PackageLicense","url" : "/services/data/v53.0/sobjects/PackageLicense/050090000019dsEAAQ"},"NamespacePrefix":"FSL","AllowedLicenses": -1,"UsedLicenses":0,"Status":"Active"},{"attributes":{"type":"PackageLicense","url":"/services/data/v53.0/sobjects/PackageLicense/050090000019dsXAAQ"},"NamespacePrefix":"einsteinplay","AllowedLicenses":-1,"UsedLicenses":0,"Status":"Active"} ]}');
        } else { feedResponseLicense = http.send(feedRequestLicense);}
      
        while (feedResponseLicense.getStatusCode() == 302) {
            feedRequestLicense.setEndpoint(feedResponseLicense.getHeader('Location'));
            feedResponseLicense = new Http().send(feedRequestLicense);
        }
        
        if ( feedResponseLicense.getStatusCode() == 200 )
        {
           LicensePackageCollection license = (LicensePackageCollection)JSON.deserialize(feedResponseLicense.getBody(), LicensePackageCollection.class); 
           
           for (integer i=0 ; i < license.records.size() ; i++) {
              // system.debug( 'lListLicensesPackage: ' +license.records[i].NamespacePrefix);
              OrgMonitoring__c orgmonitor = new OrgMonitoring__c();
              orgmonitor.OrgID__c = org.Org_Id__c;
              orgmonitor.OrgName__c = org.Label;
              orgmonitor.OrgDomainName__c = org.Org_Name__c;
              orgmonitor.Country__c = org.Country__c;
              orgmonitor.BusinessUnit__c = org.Business_Unit__c;
              orgmonitor.Timestamp__c = datetime.now();
              orgmonitor.TimestampText__c = String.valueOf( datetime.now().format('yy-MM-dd HH:mm') );
              orgmonitor.Type__c = 'License';
              orgmonitor.Name__c = license.records[i].NamespacePrefix;
              orgmonitor.LicenseCategory__c = defaultCategory;
              orgmonitor.TranslatedLicenseName__c = license.records[i].NamespacePrefix;
              orgmonitor.Total__c = license.records[i].AllowedLicenses;
              orgmonitor.Used__c = license.records[i].UsedLicenses;
              orgmonitor.Remaining__c = license.records[i].AllowedLicenses - license.records[i].UsedLicenses;
              orgmonitor.Status__c = license.records[i].Status;
              orgmonitor.Units__c = 'PackageLicense';
              orgmonitor.Latest__c = true;
              // Replace spaces with _ for each value of licence
              LicenseNamewithUnderscore = orgmonitor.Name__c.replace (' ', '_');
              LicenseNamewithUnderscore = LicenseNamewithUnderscore.replace ('-', 'x');
              if(LicenseNamewithUnderscore.length() > 40 ){
               LicenseNamewithUnderscore = LicenseNamewithUnderscore.substring(0,40);
              }
              LicenseList__mdt tln = LicenseList__mdt.getInstance(LicenseNamewithUnderscore);
              if (tln != null) {
                 orgmonitor.TranslatedLicenseName__c = tln.TranslatedLicenseName__c;
                 orgmonitor.LicenseCategory__c = tln.LicenseCategory__c;
              }
              lListLicensesPackage.add(orgmonitor);
           }
        } else {
            System.debug ('#### Error reaching endpoint for Package Licenses ==> ' +sEndPoint);
            System.debug ('#### Error code ==> ' +feedResponseLicense.getStatusCode());
           } 
        return lListLicensesPackage;

    } */
}