force-app/main/default/objects/OrgMonitoring__c/OrgMonitoring__c.object-meta.xml
<CustomObject>
    <description>This object is used to store licences and limits information for Org Monitoring</description>
    <label>OrgMonitoring</label>
    <nameField>
        <displayFormat>S{000000000}</displayFormat>
        <label>Snapshot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrgsMonitoring</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgMonitoring__c/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/Latest__c.field-meta.xml
<CustomField>
    <fullName>Latest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if this is the latest Snapshot produced</description>
    <label>Latest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/ObsoleteLoginUserList__c.field-meta.xml
<CustomField>
    <fullName>ObsoleteLoginUserList__c</fullName>
    <label>Obsolete Login User List</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/OrgDomainName__c.field-meta.xml
<CustomField>
    <fullName>OrgDomainName__c</fullName>
    <label>OrgDomainName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/OrgID__c.field-meta.xml
<CustomField>
    <fullName>OrgID__c</fullName>
    <label>Org ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/OrgName__c.field-meta.xml
<CustomField>
    <fullName>OrgName__c</fullName>
    <label>Org Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/TimestampText__c.field-meta.xml
<CustomField>
    <fullName>TimestampText__c</fullName>
    <label>TimestampText</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of limit</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <label>Units</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/OrgToMonitor__mdt.object-meta.xml
<CustomObject>
    <description>This Metadata contains the list of all orgs you want to monitor</description>
    <label>OrgToMonitor</label>
    <pluralLabel>OrgsToMonitor</pluralLabel>
</CustomObject>

force-app/main/default/objects/OrgToMonitor__mdt/fields/apiVersion__c.field-meta.xml
<CustomField>
    <fullName>apiVersion__c</fullName>
    <label>Version API</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B2B</fullName>
                <default>true</default>
                <label>B2B</label>
            </value>
            <value>
                <fullName>B2C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>The country where the Org located</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Antigua And Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Cuba</fullName>
            </value>
            <value>
                <fullName>Czech Republic (Czechia)</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>Estonia</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/DisplayObsoleteLoginUsers__c.field-meta.xml
<CustomField>
    <fullName>DisplayObsoleteLoginUsers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DisplayObsoleteLoginUsers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/ObsoleteUserDelay__c.field-meta.xml
<CustomField>
    <fullName>ObsoleteUserDelay__c</fullName>
    <label>ObsoleteUserDelay</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Org_Id__c</fullName>
    <description>This is the unique OrgId of the Org to Monitor</description>
    <label>Org ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Org_Name__c.field-meta.xml
<CustomField>
    <fullName>Org_Name__c</fullName>
    <description>This is the Name of the Org</description>
    <label>Domain Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrgMonitoringExtractObsoleteUsers.cls
/*----------------------------------------------------------------------------------------------
Author:        Salvatore Aversano
Company:       Salesforce.com
Description:   Apex class used to extract the number of users not logged in since a 
               parametrized days in the CMT OrgToMonitor
Test Class:    OrgMonitoringExtractObsoleteUsers_Test
Version:       1.0
History
               10/05/2022     Salvatore Aversano    Create version
-----------------------------------------------------------------------------------------------*/
   


public with sharing class OrgMonitoringExtractObsoleteUsers {
    
    // Wrapper Class for Obsolete Logins
    public class JSONObsoleteUsersQuery {

        public Integer totalSize;
        public Boolean done;
        public List<Records> records;
    }
    public class Attributes {
        public String type;
        public String url;
    }
    
    public class Records {
        public Attributes attributes;
        public String Id;
    }
        
    public static JSONObsoleteUsersQuery parse(String json) {
        return (JSONObsoleteUsersQuery) System.JSON.deserialize(json, JSONObsoleteUsersQuery.class);
    }

    public static boolean checkNamedCredential(String namedCredential) {
        try
        {
            NamedCredential namedCred = [SELECT Endpoint FROM NamedCredential WHERE DeveloperName = :namedCredential LIMIT 1];
        }   catch (Exception ex)
            {
              return false;  
             }
        return true;
      }

    public static OrgMonitoring__c execute (OrgToMonitor__mdt org)
    {
        /* =======================================================================
                GET USERS NOT LOGGED SINCE MORE THAN X TIME OR NEVER LOGGED IN
                         ONLY FOR USERS WITH Salesforce LICENSE.
           =======================================================================
        */
        
        // Get limit date of last login
        datetime dt = system.today().addDays( -Integer.valueOf( org.ObsoleteUserDelay__c ) );
        String d = dt.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
        OrgMonitoring__c orgmonitor = new OrgMonitoring__c(); 

        system.debug ('#### Processing Org: ' + org.DeveloperName +  ' Obsolete users not logged-in since: ' + d);

        // Check if Named credential exists 
        if(!checkNamedCredential (org.DeveloperName) ) {
            String errorMsg = '#### Named Credential ' + org.DeveloperName + ' has not been added in configuration';
            System.debug(errorMsg);
            // Prepare for error Message: The error msg is in the field ObsoleteLoginUserList__c
            orgmonitor.OrgName__c = org.DeveloperName;
            orgmonitor.Name__c = 'Error';
            orgmonitor.Latest__c = true;
            orgmonitor.ObsoleteLoginUserList__c = errorMsg;
            return orgmonitor;
        }
       
        // Prepare EndPoint 
        String sEndPoint = 'callout:' + org.DeveloperName + '/services/data/v' + org.Apiversion__c + '.0/query?q=SELECT+Id+FROM+User+WHERE+(LastLoginDate+<+' +d + '+OR+LastLoginDate+=+NULL)+and+IsActive+=+true+and+UserType+=+\'Standard\'+and+Profile.UserLicense.Name+=+\'Salesforce\'';
        sEndPoint = sEndPoint.replace('<','%3C');
        
        // Get Connexion and Run the EndPoint
        HttpRequest feedRequestUsers = new HttpRequest();
        feedRequestUsers.setEndpoint(sEndPoint);
        feedRequestUsers.setMethod('GET');
        Http http = new Http();
        HTTPResponse feedResponseUser = new HTTPResponse();
        
        if (  Test.isRunningTest() ) {
              feedResponseUser.setStatusCode( 200 );
              feedResponseUser.setBody('{"totalSize" : 1, "done" : true, "records" : [ { "attributes" : { "type" : "User", "url" : "/services/data/v53.0/sobjects/User/0057Q000003aUpqQAE" }, "Id" : "0057Q000003aUpqQAE" } ]}');
        } else 
        { 
            try {
              feedResponseUser = http.send(feedRequestUsers);
            } catch(System.UnexpectedException ex)
            {
                system.debug('Unexpected Exception in Obsolete User Class : ' + ex.getMessage());
                return null;
            }
        }
       
        while (feedResponseUser.getStatusCode() == 302) {
              feedRequestUsers.setEndpoint(feedResponseUser.getHeader('Location'));
              feedResponseUser = new Http().send(feedRequestUsers);
          }
        
          
          if ( feedResponseUser.getStatusCode() == 200 )
          {
            // system.debug( '#### Processing Obsolete Users ####');

                      
            orgmonitor.OrgID__c = org.Org_Id__c;
            orgmonitor.OrgName__c = org.Label;
        
            orgmonitor.OrgDomainName__c = org.Org_Name__c;
            orgmonitor.Country__c = org.Country__c;
            orgmonitor.BusinessUnit__c = org.Business_Unit__c;
            orgmonitor.Timestamp__c = datetime.now();
            orgmonitor.TimestampText__c = String.valueOf( datetime.now().format('yy-MM-dd HH:mm') );
            orgmonitor.Type__c = 'Users';
            orgmonitor.Name__c = 'Obsolete Logins';
            orgmonitor.Units__c = 'Unit';
            orgmonitor.Status__c = 'Active';
            orgmonitor.Latest__c = true;

            JSONObsoleteUsersQuery obsoleteUsers = (JSONObsoleteUsersQuery)JSON.deserialize(feedResponseUser.getBody(), JSONObsoleteUsersQuery.class);
            orgmonitor.Total__c = obsoleteUsers.records.size();
            system.debug( '#### There are ' + orgmonitor.Total__c + ' Obsolete Users on ' + org.DeveloperName + ' ####');
                
            //GET OBSOLETE USERS LIST ONLY IF REQUESTED IN CONFIGURATION
            if ( org.DisplayObsoleteLoginUsers__c  ) {
                String sObsoleteLoginUsers = '';
                for (integer i=0 ; i < obsoleteUsers.records.size() ; i++) 
                { 
                    String sUserId = obsoleteUsers.records[i].Id;
                    if ( sObsoleteLoginUsers == '' ) 
                    {
                        sObsoleteLoginUsers = sUserId;
                    } else {
                        sObsoleteLoginUsers += ',' + sUserId;
                    }
                }
                orgmonitor.ObsoleteLoginUserList__c = sObsoleteLoginUsers;
                orgmonitor.Total__c=obsoleteUsers.records.size();
              }       
            } else {
                String errorMsg = '#### Error code ' + feedResponseUser.getStatusCode() + ' --> Error reaching endpoint for Obsolete Users ==> ' + sEndPoint;
                System.debug(errorMsg);
                // Prepare for error Message: The error msg is in the field ObsoleteLoginUserList__c
                orgmonitor.OrgName__c = org.DeveloperName;
                orgmonitor.Name__c = 'Error';
                orgmonitor.Latest__c = true;
                orgmonitor.ObsoleteLoginUserList__c = errorMsg;
                return orgmonitor;
               } 
            return orgmonitor; 
        }
}