force-app/main/default/objects/OrgMonitoring__c/OrgMonitoring__c.object-meta.xml
<CustomObject>
    <description>This object is used to store licences and limits information for Org Monitoring</description>
    <label>OrgMonitoring</label>
    <nameField>
        <displayFormat>S{000000000}</displayFormat>
        <label>Snapshot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrgsMonitoring</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgMonitoring__c/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/Latest__c.field-meta.xml
<CustomField>
    <fullName>Latest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if this is the latest Snapshot produced</description>
    <label>Latest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/OrgDomainName__c.field-meta.xml
<CustomField>
    <fullName>OrgDomainName__c</fullName>
    <label>OrgDomainName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/OrgID__c.field-meta.xml
<CustomField>
    <fullName>OrgID__c</fullName>
    <label>Org ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/OrgName__c.field-meta.xml
<CustomField>
    <fullName>OrgName__c</fullName>
    <label>Org Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/TimestampText__c.field-meta.xml
<CustomField>
    <fullName>TimestampText__c</fullName>
    <label>TimestampText</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of limit</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <label>Units</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/OrgToMonitor__mdt.object-meta.xml
<CustomObject>
    <description>This Metadata contains the list of all orgs you want to monitor</description>
    <label>OrgToMonitor</label>
    <pluralLabel>OrgsToMonitor</pluralLabel>
</CustomObject>

force-app/main/default/objects/OrgToMonitor__mdt/fields/apiVersion__c.field-meta.xml
<CustomField>
    <fullName>apiVersion__c</fullName>
    <label>Version API</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B2B</fullName>
                <default>true</default>
                <label>B2B</label>
            </value>
            <value>
                <fullName>B2C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>The country where the Org located</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Antigua And Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Cuba</fullName>
            </value>
            <value>
                <fullName>Czech Republic (Czechia)</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>Estonia</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Org_Id__c</fullName>
    <description>This is the unique OrgId of the Org to Monitor</description>
    <label>Org ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Org_Name__c.field-meta.xml
<CustomField>
    <fullName>Org_Name__c</fullName>
    <description>This is the Name of the Org</description>
    <label>Domain Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrgMonitoringExtractLimits.cls
/*-------------------------------------------------------------------------------------
Author:        Salvatore Aversano
Company:       Salesforce.com
Description:   Apex class used to extract limits
Test Class:    OrgMoniotoringExtractLimits_Test
Version:       1.0
History
10/05/2022     Salvatore Aversano    Create version
----------------------------------------------------------------------------------------*/
public with sharing class OrgMonitoringExtractLimits {
    // Wrapper Class form Limits
    public class LimitCollection {
        public Integer Max;
        public Integer Remaining;
    }
    
    public static List<OrgMonitoring__c> execute(OrgToMonitor__mdt org)
    {    
        /* =======================================================================
                                       GET LIMITS
           =======================================================================
        */
        system.debug( '#### Processing Limits ####');
        List<OrgMonitoring__c> lListLimits = new List<OrgMonitoring__c>();
        List<String> lLimits = new list<String>();
        Integer iDataStorage = 0;

        lLimits.add('ConcurrentAsyncGetReportInstances');
        lLimits.add('ConcurrentSyncReportRuns');
        lLimits.add('DailyApiRequests');
        lLimits.add('DailyAsyncApexExecutions');
        lLimits.add('DailyBulkApiBatches');
        lLimits.add('DailyWorkflowEmails');    
        lLimits.add('HourlyAsyncReportRuns');
        lLimits.add('HourlyDashboardRefreshes');
        lLimits.add('HourlyDashboardResults');
        lLimits.add('HourlyDashboardStatuses');
        lLimits.add('MassEmail');
        lLimits.add('SingleEmail');
        lLimits.add('DataStorageMB'); // It is extracted only if the user running the program has right to
        lLimits.add('FileStorageMB'); // It is extracted only if the user running the program has right to
        
        String sEndPoint = 'callout:' + org.DeveloperName + '/services/data/v' + org.Apiversion__c + '.0/limits';
        
        // Get Connexion and Run the EndPointx
        HttpRequest feedRequestLimits = new HttpRequest();
        feedRequestLimits.setEndpoint(sEndPoint);
        feedRequestLimits.setMethod('GET');
        Http http = new Http();
        HTTPResponse feedResponseLimits = new HTTPResponse();
        if (  Test.isRunningTest() ) {
            feedResponseLimits.setStatusCode( 200 );
            feedResponseLimits.setBody ('{"ConcurrentAsyncGetReportInstances":{"Max":200,"Remaining":200},"ConcurrentSyncReportRuns":{"Max":20,"Remaining":20},"DailyApiRequests":{"Max":15000,"Remaining":14772  },"DailyAsyncApexExecutions":{"Max":250000,"Remaining":250000},"DailyBulkApiBatches":{"Max":15000,"Remaining":15000},"Ant Migration Tool":{"Max":0,"Remaining":0},"DailyWorkflowEmails":{"Max":1890,"Remaining":1890},"DataStorageMB":{"Max":5,"Remaining":4},"FileStorageMB":{"Max":20,"Remaining":20},"HourlyAsyncReportRuns":{"Max":1200,"Remaining":1200},"HourlyDashboardRefreshes":{"Max":200,"Remaining":200},"HourlyDashboardResults":{"Max":5000,"Remaining":5000},"HourlyDashboardStatuses":{"Max":999999999,"Remaining":999999999},"MassEmail":{"Max":10,"Remaining":10},"SingleEmail":{"Max":15,"Remaining":15}}' );
        } else { feedResponseLimits = http.send(feedRequestLimits);}

        while (feedResponseLimits.getStatusCode() == 302) {
            feedRequestLimits.setEndpoint(feedResponseLimits.getHeader('Location'));
            feedResponseLimits = new Http().send(feedRequestLimits);
        }

        if ( feedResponseLimits.getStatusCode() == 200 )
        {
            Map<String,LimitCollection> dcMap = (Map<String,LimitCollection>) 
                System.JSON.deserialize(feedResponseLimits.getBody(), Map<String,LimitCollection>.class);

            for ( String sLimit : dcMap.keySet() )
            {
                if (llimits.contains(sLimit))
                { 
                    OrgMonitoring__c orgmonitor = new OrgMonitoring__c();
                    orgmonitor.OrgID__c = org.Org_Id__c;
                    orgmonitor.OrgName__c = org.Label;
                    orgmonitor.OrgDomainName__c = org.Org_Name__c;
                    orgmonitor.Country__c = org.Country__c;
                    orgmonitor.BusinessUnit__c = org.Business_Unit__c;
                    orgmonitor.Timestamp__c = datetime.now();
                    orgmonitor.TimestampText__c = String.valueOf( datetime.now().format('yy-MM-dd HH:mm') );
                    orgmonitor.Type__c = 'Limits';
                    orgmonitor.Name__c = sLimit;
                    orgmonitor.Status__c = 'Active';
                    orgmonitor.Units__c = 'Unit';
                     orgmonitor.Latest__c = true;
                    orgmonitor.put('Total__c', dcMap.get(sLimit).Max);
                    orgmonitor.put('Remaining__c', dcMap.get(sLimit).Remaining);
                    orgmonitor.put('Used__c', dcMap.get(sLimit).Max - dcMap.get(sLimit).Remaining);
                    lListLimits.add(orgmonitor);

                    if ( sLimit == 'DataStorageMB' ) {
                      iDataStorage = (Integer) ( ( dcMap.get(sLimit).Max - dcMap.get(sLimit).Remaining) * 1024 );
                      if ( dcMap.get(sLimit).Max == dcMap.get(sLimit).Remaining ) iDataStorage = (Integer) dcMap.get(sLimit).Max * 1024;
                    }
                }
        }   
        } else {
            System.debug ('#### Error reaching endpoint for Limits ==> ' +sEndPoint);
            System.debug ('#### Error code ==> ' +feedResponseLimits.getStatusCode());
           } 
           
           return lListLimits;   
    }
}