force-app/main/default/objects/OrgMonitoring__c/OrgMonitoring__c.object-meta.xml
<CustomObject>
    <description>This object is used to store licences and limits information for Org Monitoring</description>
    <label>OrgMonitoring</label>
    <nameField>
        <displayFormat>S{000000000}</displayFormat>
        <label>Snapshot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrgsMonitoring</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgMonitoring__c/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/Latest__c.field-meta.xml
<CustomField>
    <fullName>Latest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if this is the latest Snapshot produced</description>
    <label>Latest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/ObsoleteLoginUserList__c.field-meta.xml
<CustomField>
    <fullName>ObsoleteLoginUserList__c</fullName>
    <label>Obsolete Login User List</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/OrgDomainName__c.field-meta.xml
<CustomField>
    <fullName>OrgDomainName__c</fullName>
    <label>OrgDomainName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/OrgID__c.field-meta.xml
<CustomField>
    <fullName>OrgID__c</fullName>
    <label>Org ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/OrgName__c.field-meta.xml
<CustomField>
    <fullName>OrgName__c</fullName>
    <label>Org Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/TimestampText__c.field-meta.xml
<CustomField>
    <fullName>TimestampText__c</fullName>
    <label>TimestampText</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of limit</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <label>Units</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/OrgToMonitor__mdt.object-meta.xml
<CustomObject>
    <description>This Metadata contains the list of all orgs you want to monitor</description>
    <label>OrgToMonitor</label>
    <pluralLabel>OrgsToMonitor</pluralLabel>
</CustomObject>

force-app/main/default/objects/OrgToMonitor__mdt/fields/apiVersion__c.field-meta.xml
<CustomField>
    <fullName>apiVersion__c</fullName>
    <label>Version API</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B2B</fullName>
                <default>true</default>
                <label>B2B</label>
            </value>
            <value>
                <fullName>B2C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>The country where the Org located</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Antigua And Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Cuba</fullName>
            </value>
            <value>
                <fullName>Czech Republic (Czechia)</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>Estonia</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Org_Id__c</fullName>
    <description>This is the unique OrgId of the Org to Monitor</description>
    <label>Org ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Org_Name__c.field-meta.xml
<CustomField>
    <fullName>Org_Name__c</fullName>
    <description>This is the Name of the Org</description>
    <label>Domain Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrgMonitoringExtractPackages.cls
/*-------------------------------------------------------------------------------------
Author:        Salvatore Aversano
Company:       Salesforce.com
Description:   Apex class used to extract installed packages
Test Class:    OrgMoniotoringExtractPackages_Test
Version:       1.0
History
10/05/2022     Salvatore Aversano    Create version
----------------------------------------------------------------------------------------*/
public with sharing class OrgMonitoringExtractPackages 
{
     // Wrapper Class for Packages
     public class DataToolingAPI {
        public List<ToolingAPIRecords> records {get;set;} 
    }

    public class SubscriberPackage {
        public String Name {get;set;} 
    }

    public class ToolingAPIRecords {
        public SubscriberPackage SubscriberPackage {get;set;} 
    }

    public static List<OrgMonitoring__c> execute(OrgToMonitor__mdt org)
    {
        /* =======================================================================
                                 GET INSTALLED PACKAGE
           =======================================================================
        */
        
        system.debug( '#### Processing Packages ####');
        List<OrgMonitoring__c> lListPackages = new List<OrgMonitoring__c>();
        String sEndPoint = 'callout:' + org.DeveloperName + '/services/data/v' + org.Apiversion__c + '.0/tooling/query/?q=SELECT+SubscriberPackage.NamespacePrefix,+SubscriberPackage.Name+FROM+InstalledSubscriberPackage';
        
        // Get Connexion and Run the EndPoint
        HttpRequest feedRequestPackage = new HttpRequest();
        feedRequestPackage.setEndpoint(sEndPoint);
        feedRequestPackage.setMethod('GET');
        Http http = new Http();
        HTTPResponse feedResponsePackage = new HTTPResponse();
        if (  Test.isRunningTest() ) {
            feedResponsePackage.setStatusCode( 200 );
            feedResponsePackage.setBody('{ "size" : 1, "totalSize" : 1, "done" : true, "queryLocator" : null, "entityTypeName" : "InstalledSubscriberPackage", "records" : [ {"attributes" : { "type" : "InstalledSubscriberPackage", "url" : "/services/data/v53.0/tooling/sobjects/InstalledSubscriberPackage/0A37Q000000TcO7SAK" }, "SubscriberPackage" : { "attributes" : { "type" : "SubscriberPackage", "url" : "/services/data/v53.0/tooling/sobjects/SubscriberPackage/03330000000wDAbAAM"}, "NamespacePrefix" : "sf_com_apps",  "Name" : "Salesforce Connected Apps" } } ]}');
        } else { feedResponsePackage = http.send(feedRequestPackage);}
       
        while (feedResponsePackage.getStatusCode() == 302) {
            feedRequestPackage.setEndpoint(feedResponsePackage.getHeader('Location'));
            feedResponsePackage = new Http().send(feedRequestPackage);
        }
        
        if ( feedResponsePackage.getStatusCode() == 200 )
        {
            DataToolingAPI dta = (DataToolingAPI)JSON.deserialize(feedResponsePackage.getBody(), DataToolingAPI.class);
            for (integer i=0 ; i < dta.records.size() ; i++)
            {
                String sPackageName = dta.records[i].SubscriberPackage.Name;
                OrgMonitoring__c orgmonitor = new OrgMonitoring__c();
                orgmonitor.OrgID__c = org.Org_Id__c;
                orgmonitor.OrgName__c = org.Label;
                orgmonitor.OrgDomainName__c = org.Org_Name__c;
                orgmonitor.Country__c = org.Country__c;
                orgmonitor.BusinessUnit__c = org.Business_Unit__c;
                orgmonitor.Timestamp__c = datetime.now();
                orgmonitor.TimestampText__c = String.valueOf( datetime.now().format('yy-MM-dd HH:mm') );
                orgmonitor.Remaining__c = 0;
                orgmonitor.Used__c = 0; 
                orgmonitor.Total__c = 0;
                orgmonitor.Type__c = 'Package';
                orgmonitor.Name__c = sPackageName;
                orgmonitor.Status__c = 'Active';
                orgmonitor.Units__c = 'Unit';
                orgmonitor.Latest__c = true; 
                lListPackages.add(orgmonitor);
            }          
        }   else {
             String errorMsg = '#### Error code ' + feedResponsePackage.getStatusCode() + ' --> Error reaching endpoint for Package ==> ' + sEndPoint;
             System.debug(errorMsg);
            
             // Prepare for error Message: The error msg is in the field ObsoleteLoginUserList__c
             OrgMonitoring__c orgmonitor = new OrgMonitoring__c();
             
             orgmonitor.OrgName__c = org.DeveloperName;
             orgmonitor.Name__c = 'Error';
             orgmonitor.Latest__c = true;
             orgmonitor.ObsoleteLoginUserList__c = errorMsg;
             lListPackages.add(orgmonitor);
             return lListPackages;
            } 
            
        return lListPackages;
    }
}