force-app/main/default/objects/OrgMonitoring__c/OrgMonitoring__c.object-meta.xml
<CustomObject>
    <description>This object is used to store licences and limits information for Org Monitoring</description>
    <label>OrgMonitoring</label>
    <nameField>
        <displayFormat>S{000000000}</displayFormat>
        <label>Snapshot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrgsMonitoring</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgMonitoring__c/fields/Latest__c.field-meta.xml
<CustomField>
    <fullName>Latest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if this is the latest Snapshot produced</description>
    <label>Latest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OrgMonitoringPurge_Test.cls
/*------------------------------------------------------------
Author:         Salvatore Aversano
Company:        Salesforce.com
Description:    Test Class
Test Class for  OrgMonitoringPurge
History
12/05/2022     Salvatore Aversano    Create version
------------------------------------------------------------*/

@isTest
public with sharing class OrgMonitoringPurge_Test {

    @isTest
    public static void OrgMonitoringPurge_Test() {

        Test.startTest();
        OrgMonitoring__c om = new OrgMonitoring__c (Latest__c = true);
        insert om;
        Database.executeBatch( new OrgMonitoringPurge(), 2000 );
        Test.stopTest();

    }
    
}