force-app/main/default/objects/OrgMonitoring__c/OrgMonitoring__c.object-meta.xml
<CustomObject>
    <description>This object is used to store licences and limits information for Org Monitoring</description>
    <label>OrgMonitoring</label>
    <nameField>
        <displayFormat>S{000000000}</displayFormat>
        <label>Snapshot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrgsMonitoring</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgMonitoring__c/fields/Latest__c.field-meta.xml
<CustomField>
    <fullName>Latest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if this is the latest Snapshot produced</description>
    <label>Latest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/ObsoleteLoginUserList__c.field-meta.xml
<CustomField>
    <fullName>ObsoleteLoginUserList__c</fullName>
    <label>Obsolete Login User List</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/OrgCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>OrgCreatedDate__c</fullName>
    <description>The date of creation of the org.</description>
    <label>OrgCreatedDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/OrgToMonitor__mdt.object-meta.xml
<CustomObject>
    <description>This Metadata contains the list of all orgs you want to monitor</description>
    <label>OrgToMonitor</label>
    <pluralLabel>OrgsToMonitor</pluralLabel>
</CustomObject>

force-app/main/default/objects/OrgToMonitor__mdt/fields/apiVersion__c.field-meta.xml
<CustomField>
    <fullName>apiVersion__c</fullName>
    <label>Version API</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B2B</fullName>
                <default>true</default>
                <label>B2B</label>
            </value>
            <value>
                <fullName>B2C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>The country where the Org located</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Antigua And Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Cuba</fullName>
            </value>
            <value>
                <fullName>Czech Republic (Czechia)</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>Estonia</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/DisplayObsoleteLoginUsers__c.field-meta.xml
<CustomField>
    <fullName>DisplayObsoleteLoginUsers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DisplayObsoleteLoginUsers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/ObsoleteUserDelay__c.field-meta.xml
<CustomField>
    <fullName>ObsoleteUserDelay__c</fullName>
    <label>ObsoleteUserDelay</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Org_Id__c</fullName>
    <description>This is the unique OrgId of the Org to Monitor</description>
    <label>Org ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Org_Name__c.field-meta.xml
<CustomField>
    <fullName>Org_Name__c</fullName>
    <description>This is the Name of the Org</description>
    <label>Domain Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/OrgCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>OrgCreatedDate__c</fullName>
    <description>Date of creation of the Org</description>
    <inlineHelpText>Creation date of the Organization</inlineHelpText>
    <label>OrgCreatedDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/OrgMonitoringQueueable_Test.cls
/*------------------------------------------------------------
Author:         Salvatore Aversano
Company:        Salesforce.com
Description:    Test Class
Test Class for  OrgMonitoringQueueable
History
16/05/2022     Salvatore Aversano    Create version
------------------------------------------------------------*/
@isTest
public with sharing class OrgMonitoringQueueable_Test {

    @isTest
    public static void OrgMonitoringQueueable_Test() {
        
       
        Test.startTest();
       
        List<OrgToMonitor__mdt> lorgs = new List<OrgToMonitor__mdt>();
        for (integer i=0 ; i < 11 ; i++) 
        {
         OrgToMonitor__mdt mdt = new OrgToMonitor__mdt();
         mdt.DeveloperName                = 'TEST-' +i ;
         mdt.Org_Id__c                    = '00Dxxxxxxxxxxx' +i;
         mdt.Org_Name__c                  = 'TEST-ORG';
         mdt.OrgCreatedDate__c            =  System.today();
         mdt.Country__c                   = 'France';
         mdt.Business_Unit__c             = 'B2B';
         mdt.ObsoleteUserDelay__c         = 2;
         mdt.DisplayObsoleteLoginUsers__c = true;
         mdt.apiVersion__c                = '56';
         lorgs.add(mdt);
        }      
        OrgMonitoring__c om = new OrgMonitoring__c (Latest__c = true, Name__c = 'Error', ObsoleteLoginUserList__c = 'Error Message');
        insert om;

        System.enqueueJob(new OrgMonitoringQueueable(lorgs));
        Test.stopTest();

    }
    
}