force-app/main/default/objects/OrgMonitoring__c/OrgMonitoring__c.object-meta.xml
<CustomObject>
    <description>This object is used to store licences and limits information for Org Monitoring</description>
    <label>OrgMonitoring</label>
    <nameField>
        <displayFormat>S{000000000}</displayFormat>
        <label>Snapshot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrgsMonitoring</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgMonitoring__c/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/Latest__c.field-meta.xml
<CustomField>
    <fullName>Latest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if this is the latest Snapshot produced</description>
    <label>Latest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/OrgID__c.field-meta.xml
<CustomField>
    <fullName>OrgID__c</fullName>
    <label>Org ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/OrgInstance__c.field-meta.xml
<CustomField>
    <fullName>OrgInstance__c</fullName>
    <label>OrgInstance</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/OrgName__c.field-meta.xml
<CustomField>
    <fullName>OrgName__c</fullName>
    <label>Org Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of limit</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoring__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <label>Units</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoringPod__c/OrgMonitoringPod__c.object-meta.xml
<CustomObject>
    <label>OrgMonitoringPod</label>
    <nameField>
        <label>OrgMonitoringPod Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrgMonitoringPods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgMonitoringPod__c/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <label>BusinessUnit</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoringPod__c/fields/MasterPod__c.field-meta.xml
<CustomField>
    <fullName>MasterPod__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MasterPod</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrgMonitoringPod__c/fields/Pod__c.field-meta.xml
<CustomField>
    <fullName>Pod__c</fullName>
    <label>Pod</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrgMonitoringPodAvailabilityChecker.cls
/*-------------------------------------------------------------------------------------
Author:        Salvatore Aversano
Company:       Salesforce.com
Description:   Apex class used to check the availability of all Pods used by ENGIE instances
Test Class:    OrgMonitoringPodAvailabilityChecker_Test
Version:       0.1
History
23/02/2024     Salvatore Aversano    Create version

Version 0.1    Created
----------------------------------------------------------------------------------------*/

public with sharing class OrgMonitoringPodAvailabilityChecker implements Schedulable
{
    public void execute (SchedulableContext sc )
    {
        System.enqueueJob (new QueueableExtraction());
    }
    
    public class QueueableExtraction implements Queueable, Database.AllowsCallouts
    {
        public void execute(QueueableContext context) 
        {
            List<OrgMonitoringPod__c> podToInsert = new List<OrgMonitoringPod__c>();
            List<OrgMonitoring__c> orgslist = extractPods();
            Set <String> SetPodToCheck = new Set<String>();
            
            for ( OrgMonitoring__c oOrg : orgslist ) 
            {
                checkPodAvailability(SetPodToCheck, podToInsert, oOrg);
            }

            // insert records 
            if(podToInsert!=null && !podToInsert.isEmpty())
            {
                try {
                insert podToInsert;
                } catch (DMLException f){
                  System.debug('#### DML Exception : ' + f);
                }
            }
        }
    }
        // Method to check the availability of a POD
        public static void checkPodAvailability(Set <String> Pods, List<OrgMonitoringPod__c> podToInsert, OrgMonitoring__c  org) 
        {
            String apiUrl = 'https://api.status.salesforce.com/v1/instances/';
            apiUrl += org.OrgInstance__c + '/status/preview';
            // Prepare a new record for OrgMonitoringPod
            OrgMonitoringPod__c orgPod = new OrgMonitoringPod__c();
            String podStatus = ' ';
            orgPod.MasterPod__c = false;
            orgPod.OrgId__c = org.OrgId__c;
            orgPod.OrgName__c = org.OrgName__c;      
            orgPod.Country__c = org.Country__c;
            orgPod.BusinessUnit__c = org.BusinessUnit__c;
            orgPod.Pod__c = org.OrgInstance__c;
            orgPod.Status__c = podstatus;

            if (alreadyCheckedPod(Pods, org.OrgInstance__c)) 
            { 
                podToInsert.add(orgPod); // POD has been already checked
            }   else 
                {  
                    // Make HTTP request to the Salesforce status API
                    HttpRequest request = new HttpRequest();
                    request.setEndpoint(apiUrl);
                    request.setMethod('GET');
                    Http http = new Http();
                    HttpResponse response = http.send(request);

                    // Check if the request was successful
                    if (response.getStatusCode() == 200) 
                    {
                        // Parse the response JSON
                        Map<String, Object> jsonResponse = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());                  
                        // Get the availability status
                        podStatus = (String)jsonResponse.get('status');
                        // Insert a new record into OrgMonitoringPod
                        orgPod.MasterPod__c = true;
                        orgPod.Status__c = podstatus;
                        podToInsert.add(orgPod);
                        // system.debug ('Pod Controlé :' + org.OrgInstance__c + ' Org Id : ' + orgPod.OrgId__c + ' Status = ' +podStatus + ' Date : '+ orgPod.Datetime__c  + ' Time : ' +orgPod.Time__c + ' MasterPOd = ' +orgPod.MasterPod__c);
                    } else 
                      {
                         // If request was not successful, return an error message
                         orgPod.Status__c = 'NA';
                         podToInsert.add(orgPod);
                      } 
                }
        }  

        // Method to extract the PODs list for all configured Orgs
        private static List<OrgMonitoring__c> extractPods()
        {
            return [SELECT OrgId__c, OrgName__c, OrgInstance__c, Country__c, BusinessUnit__c FROM OrgMonitoring__c where latest__c = true and Type__c = 'License' and Units__c = 'UserLicense' and Name__c = 'Salesforce'];
        }
    
        // Method to check if a numPOD has already been checked 
        public static Boolean alreadyCheckedPod (Set <String> Pods, String podToCheck)
        {
         if (Pods.contains(podToCheck))
          {
            // system.debug ('Contient : ' +podToCheck);
            return true;
          } else {
                // system.debug ('Ne Contient pas : ' +podToCheck);
                Pods.add(podToCheck);
                return false;
            }
        }
}   