force-app/main/default/objects/OrgMonitoringPod__c/OrgMonitoringPod__c.object-meta.xml
<CustomObject>
    <label>OrgMonitoringPod</label>
    <nameField>
        <label>OrgMonitoringPod Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrgMonitoringPods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgMonitoringPod__c/fields/MasterPod__c.field-meta.xml
<CustomField>
    <fullName>MasterPod__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MasterPod</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrgMonitoringPod__c/fields/Pod__c.field-meta.xml
<CustomField>
    <fullName>Pod__c</fullName>
    <label>Pod</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrgMonitoringPodPurge_Test.cls
/*------------------------------------------------------------
Author:         Salvatore Aversano
Company:        Salesforce.com
Description:    Test Class
Test Class for  OrgMonitoringPodPurge
History
28/02/2024     Salvatore Aversano    Create version
------------------------------------------------------------*/

@isTest
public with sharing class OrgMonitoringPodPurge_Test {
   
    public static String CRON_EXP = '0 0 0 31 12 ? 2024';

    @isTest
    public static void OrgMonitoringPodPurge_Test() {
        
        Test.startTest();
        OrgMonitoringPod__c om = new OrgMonitoringPod__c (Pod__c = 'TEST', MasterPod__c = true, Status__c = 'OK');
        insert om;
        Database.executeBatch( new OrgMonitoringPodPurge(), 2000 );

        // Schedule the test job
        String jobId = System.schedule('Test class for OrgMonitoringPodPurge', CRON_EXP, new OrgMonitoringPodPurge());
       
        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
        NextFireTime
        FROM CronTrigger WHERE id = :jobId];

        // Verify the expressions are the same
        System.assertEquals(CRON_EXP, ct.CronExpression);

        // Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered);

        // Verify the next time the job will run
        System.assertEquals('2024-12-31 00:00:00',  String.valueOf(ct.NextFireTime));
        Test.stopTest();

    }
}