force-app/main/default/objects/OrgMonitoringPod__c/OrgMonitoringPod__c.object-meta.xml
<CustomObject>
    <label>OrgMonitoringPod</label>
    <nameField>
        <label>OrgMonitoringPod Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrgMonitoringPods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgMonitoringPod__c/fields/MasterPod__c.field-meta.xml
<CustomField>
    <fullName>MasterPod__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MasterPod</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrgMonitoringPod__c/fields/Pod__c.field-meta.xml
<CustomField>
    <fullName>Pod__c</fullName>
    <label>Pod</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgMonitoringPodHistory__c/OrgMonitoringPodHistory__c.object-meta.xml
<CustomObject>
    <label>OrgMonitoringPodHistory</label>
    <nameField>
        <label>OrgMonitoringPodHistory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrgMonitoringPodHistory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgMonitoringPodHistory__c/fields/Availability__c.field-meta.xml
<CustomField>
    <fullName>Availability__c</fullName>
    <label>Availability</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrgMonitoringPodHistory__c/fields/nbKO__c.field-meta.xml
<CustomField>
    <fullName>nbKO__c</fullName>
    <label>nbKO</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrgMonitoringPodHistory__c/fields/nbOK__c.field-meta.xml
<CustomField>
    <fullName>nbOK__c</fullName>
    <label>nbOK</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OrgMonitoringPodHistorize_Test.cls
/*------------------------------------------------------------
Author:         Salvatore Aversano
Company:        Salesforce.com
Description:    Test Class
Test Class for  OrgMoniotoringPodHistorize
History
09/04/2024     Salvatore Aversano    Create version
------------------------------------------------------------*/
@isTest
public class OrgMonitoringPodHistorize_Test {
    @isTest
    static void testProcessScope() {
        // Create test data
        List<OrgMonitoringPod__c> scope = new List<OrgMonitoringPod__c>();
        OrgMonitoringPod__c pod1 = new OrgMonitoringPod__c();
        pod1.Pod__c = 'TestPod1';
        pod1.CreatedDate = Date.today();
        pod1.status__c = 'OK';
        pod1.masterpod__c = true;
        scope.add(pod1);

        OrgMonitoringPod__c pod2 = new OrgMonitoringPod__c();
        pod2.Pod__c = 'TestPod2';
        pod2.CreatedDate = Date.today();
        pod2.status__c = 'KO';
        pod2.masterpod__c = true;
        scope.add(pod2);

        // Call the method under test
        Test.startTest();
        OrgMonitoringPodHistorize.processScope(scope);
        Test.stopTest();

        // Query the historized records and assert the results
        List<OrgMonitoringPodHistory__c> histPods = [SELECT Pod__c, Month__c, Year__c, nbOK__c, nbKO__c, Availability__c FROM OrgMonitoringPodHistory__c];
        System.assertEquals(2, histPods.size(), 'Number of historized records should be 2');

        OrgMonitoringPodHistory__c histPod = histPods[0];
        System.assertEquals('TestPod1', histPod.Pod__c, 'Pod assert error');
        Datetime today = Date.today();
        System.assertEquals(today.format('MMMM'), histPod.Month__c,'Month assert error');
        System.assertEquals(String.valueOf(Date.today().year()), histPod.Year__c, 'Year assert error');
        System.assertEquals(1, histPod.nbOK__c, 'nbOK assert error');
        System.assertEquals(100.0000, histPod.Availability__c, 'Availability assert error');
    }
}