force-app/main/default/objects/OrgToMonitor__mdt/OrgToMonitor__mdt.object-meta.xml
<CustomObject>
    <description>This Metadata contains the list of all orgs you want to monitor</description>
    <label>OrgToMonitor</label>
    <pluralLabel>OrgsToMonitor</pluralLabel>
</CustomObject>

force-app/main/default/objects/OrgToMonitor__mdt/fields/apiVersion__c.field-meta.xml
<CustomField>
    <fullName>apiVersion__c</fullName>
    <label>Version API</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B2B</fullName>
                <default>true</default>
                <label>B2B</label>
            </value>
            <value>
                <fullName>B2C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>The country where the Org located</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Antigua And Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Cuba</fullName>
            </value>
            <value>
                <fullName>Czech Republic (Czechia)</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>Estonia</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/DisplayObsoleteLoginUsers__c.field-meta.xml
<CustomField>
    <fullName>DisplayObsoleteLoginUsers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DisplayObsoleteLoginUsers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/ObsoleteUserDelay__c.field-meta.xml
<CustomField>
    <fullName>ObsoleteUserDelay__c</fullName>
    <label>ObsoleteUserDelay</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Org_Id__c</fullName>
    <description>This is the unique OrgId of the Org to Monitor</description>
    <label>Org ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/Org_Name__c.field-meta.xml
<CustomField>
    <fullName>Org_Name__c</fullName>
    <description>This is the Name of the Org</description>
    <label>Domain Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgToMonitor__mdt/fields/OrgCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>OrgCreatedDate__c</fullName>
    <description>Date of creation of the Org</description>
    <inlineHelpText>Creation date of the Organization</inlineHelpText>
    <label>OrgCreatedDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/OrgMonitoringQueueableRunner.cls
public with sharing class OrgMonitoringQueueableRunner implements Queueable, Database.AllowsCallouts{
    public void execute(QueueableContext context) 
    {
        integer counter=0;
        try
        {
            List<OrgToMonitor__mdt> lorgs = new List<OrgToMonitor__mdt>([SELECT DeveloperName, Org_Id__c, Label, Org_Name__c, OrgCreatedDate__c, Country__c, Business_Unit__c, ObsoleteUserDelay__c, DisplayObsoleteLoginUsers__c, apiVersion__c FROM OrgToMonitor__mdt order by label]);
            system.debug('record to process...'+lorgs.size());
            
            if (lorgs !=null && !lorgs.isEmpty()) {
                List<String> orgs = new List<String>{};
                OrgMonitoringQueueableRun.oldRecords(orgs);
                OrgMonitoringQueueable esync = new OrgMonitoringQueueable(lorgs);
                System.enqueueJob(esync);
            }
        }
        catch(Exception ex)
        {
            system.debug('Exception in OrgMonitoringQueueableRunner:'+ex.getMessage());
        }
    }
}